const userTypes = {
    EMAIL_LOGIN_START : 'EMAIL_LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    USER_AUTH_SESSION: 'USER_AUTH_SESSION',
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

    REGISTER_USER_START: 'REGISTER_USER_START',
    REGISTER_ERROR: 'REGISTER_ERROR',
    
    RESET_PASSWORD_START: 'RESET_PASSWORD_START',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    
    RESET_USER_STATE: 'RESET_USER_STATE',
    
    GOOGLE_LOGIN_START : 'GOOGLE_LOGIN_START',

    
};

export default userTypes;